import "./globals.css";

export const metadata = {
  title: "Code Café",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.ico", sizes: "any" }],
    apple: [{ url: "/logo192.png", sizes: "192x192" }],
  },
  manifest: "/manifest.json",
};

// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
